### ISSUE TITLE
Won't compile

### ISSUE THREAD

**Issue by spatrickapps** [harrisonapps/Universal-Video-Downloader#3]
when i try to compile i get this error 

.stamp', needed by `internal-library-all_'.  Stop.

> grep: /Users/macbook/Downloads/Universal-Video-Downloader-master/Universal Video Downloader: Is a directory
> grep: /Users/macbook/Downloads/Universal-Video-Downloader-master/Universal Video Downloader: Is a directory
> grep: /Users/macbook/Downloads/Universal-Video-Downloader-master/Universal Video Downloader: Is a directory
> /opt/theos/makefiles/rules.mk:39: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/master/rules.mk:77: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/rules.mk:39: warning: overriding commands for target `Video'
> /opt/theos/makefiles/master/rules.mk:77: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/rules.mk:39: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/master/rules.mk:77: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/rules.mk:42: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/rules.mk:39: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/rules.mk:42: warning: overriding commands for target `Video'
> /opt/theos/makefiles/rules.mk:39: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/rules.mk:42: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/rules.mk:39: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/rules.mk:45: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/rules.mk:42: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/rules.mk:45: warning: overriding commands for target `Video'
> /opt/theos/makefiles/rules.mk:42: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/rules.mk:45: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/rules.mk:42: warning: ignoring old commands for target `Downloader'
> make: Circular /Users/macbook/Downloads/Universal-Video-Downloader-master/Universal <- /Users/macbook/Downloads/Universal-Video-Downloader-master/Universal dependency dropped.
> make: Circular Video <- /Users/macbook/Downloads/Universal-Video-Downloader-master/Universal dependency dropped.
> make: Circular Video <- Video dependency dropped.
> make: Circular Downloader <- /Users/macbook/Downloads/Universal-Video-Downloader-master/Universal dependency dropped.
> make: Circular Downloader <- Video dependency dropped.
> make: Circular Downloader <- Downloader dependency dropped.
> make: Circular Downloader <- /Users/macbook/Downloads/Universal-Video-Downloader-master/Universal dependency dropped.
> make: Circular Downloader <- Video dependency dropped.
> make: Circular Downloader <- Downloader dependency dropped.
> make: Circular Video <- /Users/macbook/Downloads/Universal-Video-Downloader-master/Universal dependency dropped.
> make: Circular Video <- Video dependency dropped.
> make: Circular /Users/macbook/Downloads/Universal-Video-Downloader-master/Universal <- /Users/macbook/Downloads/Universal-Video-Downloader-master/Universal dependency dropped.
> > Making all for tweak UVD…
> /opt/theos/makefiles/instance/rules.mk:179: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:170: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:179: warning: overriding commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:170: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:179: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:170: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:183: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:179: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:183: warning: overriding commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:179: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:183: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:179: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:192: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:183: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:192: warning: overriding commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:183: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:192: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:183: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:196: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:192: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:196: warning: overriding commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:192: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:196: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:192: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:205: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:196: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:205: warning: overriding commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:196: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:205: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:196: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:209: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:205: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:209: warning: overriding commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:205: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:209: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:205: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:213: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:209: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:213: warning: overriding commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:209: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:213: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:209: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:222: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:213: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:222: warning: overriding commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:213: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:222: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:213: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:231: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:222: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:231: warning: overriding commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:222: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:231: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:222: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:240: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:231: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:240: warning: overriding commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:231: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:240: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:231: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:249: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:240: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:249: warning: overriding commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:240: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:249: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:240: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:258: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:249: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:258: warning: overriding commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:249: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:258: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:249: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:267: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:258: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:267: warning: overriding commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:258: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:267: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:258: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:271: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:267: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:271: warning: overriding commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:267: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:271: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:267: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:276: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:271: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:276: warning: overriding commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:271: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:276: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:271: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:282: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:276: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:282: warning: overriding commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:276: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:282: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:276: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:288: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:282: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:288: warning: overriding commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:282: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:288: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:282: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:294: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:288: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:294: warning: overriding commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:288: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:294: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:288: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/rules.mk:39: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/rules.mk:294: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/rules.mk:39: warning: overriding commands for target `Video'
> /opt/theos/makefiles/instance/rules.mk:294: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/rules.mk:39: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/instance/rules.mk:294: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/rules.mk:42: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/rules.mk:39: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/rules.mk:42: warning: overriding commands for target `Video'
> /opt/theos/makefiles/rules.mk:39: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/rules.mk:42: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/rules.mk:39: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/rules.mk:45: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/rules.mk:42: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/rules.mk:45: warning: overriding commands for target `Video'
> /opt/theos/makefiles/rules.mk:42: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/rules.mk:45: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/rules.mk:42: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/instance/library.mk:32: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/rules.mk:45: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/library.mk:32: warning: overriding commands for target `Video'
> /opt/theos/makefiles/rules.mk:45: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/instance/library.mk:32: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/rules.mk:45: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/instance/library.mk:32: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/library.mk:32: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/library.mk:32: warning: overriding commands for target `Video'
> /opt/theos/makefiles/instance/library.mk:32: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/instance/library.mk:32: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/instance/library.mk:32: warning: ignoring old commands for target `Downloader'
> /opt/theos/makefiles/instance/library.mk:32: warning: overriding commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/library.mk:32: warning: ignoring old commands for target `/Users/macbook/Downloads/Universal-Video-Downloader-master/Universal'
> /opt/theos/makefiles/instance/library.mk:32: warning: overriding commands for target `Video'
> /opt/theos/makefiles/instance/library.mk:32: warning: ignoring old commands for target `Video'
> /opt/theos/makefiles/instance/library.mk:32: warning: overriding commands for target `Downloader'
> /opt/theos/makefiles/instance/library.mk:32: warning: ignoring old commands for target `Downloader'
> make[1]: *** No rule to make target `.stamp', needed by `internal-library-all_'.  Stop.
> make: *** [UVD.all.tweak.variables] Error 2

**Comment by harrisonapps** [comment]
You'll need to remove the spaces from the directory names first.

**Comment by spatrickapps** [comment]
well i feel stupid. Thank you very much

**Comment by spatrickapps** [comment]
I'm trying to contact you and i was wondering if your email is still the following,  harrisonapps@gmail.com

**Comment by harrisonapps** [comment]
It is now support@harrisonapps.com
